parameters:
    env(MASSIVE_SEARCH_PREFIX): 'massive'
    env(ELASTICSEARCH_HOST): '127.0.0.1:9200'

massive_search:
    metadata:
        prefix: '%env(resolve:MASSIVE_SEARCH_PREFIX)%'
    adapter: elastic
    adapters:
        elastic:
            version: 7.8
            hosts:
                - '%env(resolve:ELASTICSEARCH_HOST)%'
